services:
  database:
    image: mysql:8.4.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      TZ: Asia/Taipei
    command: [
      --character-set-server=utf8mb4,
      --collation-server=utf8mb4_unicode_ci
    ]
    volumes:
      - ./database/schemas:/docker-entrypoint-initdb.d:ro
      - membership-system:/var/lib/mysql
    ports:
      - "${DATABASE_PORT}:3306"
    networks:
      - default

networks:
  default:
    name: membership-system

volumes:
  membership-system:
